//Teste de requisições - Categoria

@baseURL = http://localhost:4000
@id = 6064fdfe45d3970342761d53

###
// GET - Lista as categorias
GET {{baseURL}}/categorias
Content-Type: application/json

###
// GET - Lista a categoria pelo ID
GET {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
// POST - Inclui uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{"nome": "Cantinas", 
"status": "ativo",
"foto": {
       "originalname": "massas.png", 
       "path": "publics/uploads/massas.png",
       "size": 20771, 
       "mimetype":"image/png"
  }
}

###
// POST - Inclui uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{"nome": "Churrascarias", 
"status": "ativo",
"foto": {
       "originalname": "fire.png", 
       "path": "publics/uploads/fire.png",
       "size": 19873, 
       "mimetype":"image/png"
  } 
}

###
// DELETE - Apaga uma categoria
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
// PUT - Altera a categoria
PUT {{baseURL}}/categorias
Content-Type: application/json

{
"_id" : "6064fdfe45d3970342761d53",
"nome" : "Churrascaria",
"status": "ativo"
}
